//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_OS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Contacto
    {
         public Contacto()
        {
            this.Cuenta = new HashSet<Cuenta>();
        }
        [Key]
        public int idContacto { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string estadoCivil { get; set; }
        public int idCargo { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual ICollection<Cuenta> Cuenta { get; set; }
    }
}
