//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_OS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Cuenta
    {
         public Cuenta()
        {
            this.Actividad = new HashSet<Actividad>();
            this.OportunidadNegocio = new HashSet<OportunidadNegocio>();
            this.Contacto = new HashSet<Contacto>();
        }
        [Key]
        public int idCuenta { get; set; }
        public string tipoCuenta { get; set; }
        public string tipoDocumento { get; set; }
        public string nroDocumento { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string sitioWeb { get; set; }
        public string rubro { get; set; }
        public int idCiudad { get; set; }
        public int idColaboradorAsignado { get; set; }
        public string estado { get; set; }
    
       public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual Colaborador Colaborador { get; set; }
        public virtual ICollection<OportunidadNegocio> OportunidadNegocio { get; set; }
       public virtual ICollection<Contacto> Contacto { get; set; }
    }
}
