//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_OS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class OportunidadNegocio
    {
        public OportunidadNegocio()
        {
            this.Propuesta = new HashSet<Propuesta>();
        }
        [Key]
        public int idOportunidad { get; set; }
        public string necesidadCuenta { get; set; }
        public decimal presupuesto { get; set; }
        public System.TimeSpan TiempoTomaDecision { get; set; }
        public int idEncargadoTomaDecision { get; set; }
        public int idCuenta { get; set; }
        public int idProducto { get; set; }
        public string estado { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual ICollection<Propuesta> Propuesta { get; set; }
    }
}
