//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_OS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public  class Producto
    {
        public Producto()
        {
            this.OportunidadNegocio = new HashSet<OportunidadNegocio>();
        }
        [Key]
        public int idProducto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int idTipo { get; set; }
    
        public virtual ICollection<OportunidadNegocio> OportunidadNegocio { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
