//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_OS.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Usuario
    {
        public Usuario()
        {
            this.Colaborador = new HashSet<Colaborador>();
        }
        [Key]
        public int idUsuario { get; set; }
        public string login { get; set; }
        public string contraseña { get; set; }
        public int idPerfil { get; set; }
    
        public virtual ICollection<Colaborador> Colaborador { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
